### ISSUE TITLE
Lend Button Styling and Routing

### ISSUE THREAD

**Issue by sekharp** [sekharp/the_pivot#35]
-When you hit the lend button after entering an amount, you should be routed to the cart, and there should be a flash message
-Do not allow an improper or overly large amount or negative amount, or any non-numerical or non-monetary amount, or one with too many decimals
-Also the button should be styled blue like all the other buttons on the site

**Comment by patwey** [comment]
Lend button now routes to cart, and there is a flash message that returns you to the project you just added a loan for.
